# Bonus Task 2 

Numpy and pandas

Imports

In [2]:
import numpy as np
import seaborn as sns

# Bonus Task 2 - Numpy Section

### 1.1. Create a 1D array containing 20 evenly spaced values between 0 and 1

In [3]:
array_1_to_20 = np.linspace(0, 1, 20)
print(array_1_to_20)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


### 1.2. Create an array containing values from 0 to 99 and reshape it into a 5x20 matrix.

In [8]:
# Luodaan 1d array 0-99 luvuilla
array_0_to_99 = np.arange(100)
print("1D array: \n", array_0_to_99)

# Luodaan 1d arraysta 5x20 matrix
array_0_to_99_reshape = array_0_to_99.reshape(5, 20)
print("Reshaped array: \n",  array_0_to_99_reshape)


1D array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Reshaped array: 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


### 1.3. Create a random vector of length 15 and calculate its mean and standard deviation.

In [4]:
# Create random vector length 15
vector_random = np.random.random(15)
print("Random vector: \n", vector_random)

# Calculate mean
vector_mean = np.mean(vector_random)
print("Mean of vector: \n", vector_mean)

# Calculate standard deviation
vector_deviation = np.std(vector_random)
print("Standard deviation: \n", vector_deviation)

Random vector: 
 [0.86305212 0.3549525  0.13371465 0.80458498 0.10372998 0.30205591
 0.18657522 0.18260223 0.16257021 0.80802902 0.51048653 0.66564637
 0.82673316 0.10768157 0.26284428]
Mean of vector: 
 0.4183505813609336
Standard deviation: 
 0.28614355212506387


# Bonus Task 2 - Pandas Section - Titanic

Ladataan datasetti

In [8]:
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### 2.1. Calculate the survival percentages of Titanic passengers based on gender and travel class (1st, 2nd, 3rd class).

Eli missä katsotaan kuinka monta prosenttia selviytyjistä on ollut naisia ja missä luokassa

(Huom. tässä käytettiin ChatGtp:tä. Sain kaksi eri tapaa toteuttaa mitkä molemmat toimivat hyvin. Valitsin tämän, koska esitystapa oli kaikista paras. )

In [9]:
pivot = (
    titanic
    .pivot_table(
        index='sex',
        columns='class',
        values='survived',
        aggfunc='mean'
    )
    * 100                   # kerrotaan sadalla
)
print(pivot)

class       First     Second      Third
sex                                    
female  96.808511  92.105263  50.000000
male    36.885246  15.740741  13.544669


C:\Users\USER\AppData\Local\Temp\ipykernel_14976\211586647.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  .pivot_table(


### 2.2. Did ticket price (Fare) have an impact on survival?

Hint: Group the ticket price by travel class and use the agg() function to analyze the average.



In [10]:
pivot_fare = (
    titanic
    .groupby(['survived', 'class'])['fare']
    .agg(mean='mean', count='count')             # saa arvot välillä 0–1
    .reset_index()        # saadaan DataFrame-muoto takaisin
)

print(pivot_fare)

   survived   class       mean  count
0         0   First  64.684007     80
1         0  Second  19.412328     97
2         0   Third  13.669364    372
3         1   First  95.608029    136
4         1  Second  22.055700     87
5         1   Third  13.694887    119


C:\Users\USER\AppData\Local\Temp\ipykernel_14976\454203725.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(['survived', 'class'])['fare']
