## Numpy | 3. tunti

Tällä tunnilla vasta annetaan 2. tehtävä. 


In [1]:
!pip3 install numpy


[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: c:\Users\USER\Desktop\AMK2022\25K\Data analytics\EkaAsennus\.venv\Scripts\python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix1
matrix1.shape
matrix1.ndim

2

In [6]:
matrix2 = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])


In [7]:
np.dot(matrix1, matrix2)

array([[12, 12, 12],
       [30, 30, 30],
       [48, 48, 48]])

### Statistica

In [9]:
data = np.array([1,1,1,2,2,1,1,3,2,6,10,11])

In [ ]:
print(f'mean: {round(np.mean(data))}')
print(f'median: {np.median(data)}')
print(f'variance: {np.var(data)}')
print(f'std: {np.std(data)}')


mean: 3
median: 2.0
variance: 11.909722222222223


In [12]:
x = np.array([10, 11, 12, 13])
y = np.array([1, 2, 3, 4])

print(f'correof: {np.corrcoef(x, y)}')


correof: [[1. 1.]
 [1. 1.]]


In [13]:
np.cov(x, y)

array([[1.66666667, 1.66666667],
       [1.66666667, 1.66666667]])

In [ ]:
# How to access tables (last element)
x[-1]

np.int64(13)

In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix[1,1]


np.int64(5)

In [ ]:
matrix[:,1]
# valitse kaikki mutta kaikista vain toinen luku

array([2, 5, 8])

In [17]:
matrix[:2,:2]

array([[1, 2],
       [4, 5]])

In [20]:
# Editing

new_matrix = matrix.copy()
new_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
new_matrix.transpose()
# all the columns are swapped

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
new_matrix.ravel()
# make one dimensional array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
narr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
narr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
a1, a2 = np.hsplit(narr, 2)
a1, a2

(array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]]))

In [ ]:
np.hstack([a1, a2]) # stakkaa back together

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Pandas | 3. tunti


- works on top of numpy
- Pandas series, one dimensional data structure