## Numpy

In [3]:
!pip3 install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.5 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/12.6 MB 1.7 MB/s eta 0:00:08
   ---- ----------------------------------- 1.3/12.6 MB 1.9 MB/s eta 0:00:07
   ----- ---------------------------------- 1.8/12.6 MB 2.0 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.6 MB 2.1 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.6 MB 2.2 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.6 MB 2.2 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.6 MB 2.3 MB/s eta 0:00:04
   -------------- ------------------------- 4.7/12.6 MB 2.3 MB/s eta 0:00:04
   ----------------- ---------------------- 5.5/12.6 MB 2.4 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.6 MB 2.5 MB/s eta 0:00:03
   ----------


[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [ ]:
our_array = np.array([1, 2, 34, 2])
# one dimensional

In [ ]:
np.array([[1, 2, 34, 2],[1, 2, 34, 2]])
# too dimensional

In [ ]:
np.zeros([3, 3])

In [ ]:
np.arrange(-5, 6, 2)

In [ ]:
np.linspace(0, 1, 10)

In [ ]:
np.random.random(10)

### Normally distributed dataset

In [ ]:
np.random.normal(0, 100, 10)

### Info about the ndarray

In [5]:
data = np.array([[1, 2, 34, 2],[1, 2, 34, 2]])

In [ ]:
data.shape
# (2, 4)

(2, 4)

In [ ]:
data.dtype
# data.dtype --> Datatype

dtype('int64')

In [ ]:
data.size
# 8

8

In [ ]:
data.ndim
# 2

2

### Basic operations


In [10]:
a = np.array([1, 2, 34, 2])
b = np.array([1, 3, 0, 2])

In [ ]:
a+b
# array([ 2,  5, 34,  4])

array([ 2,  5, 34,  4])

In [ ]:
[1, 3, 0, 2] + [1, 3, 0, 2]
# Basic Python [1, 3, 0, 2] + [1, 3, 0, 2]

[1, 3, 0, 2, 1, 3, 0, 2]

In [ ]:
np.sqrt(a)
# array([1.        , 1.41421356, 5.83095189, 1.41421356])

array([1.        , 1.41421356, 5.83095189, 1.41421356])

In [ ]:
np.exp(a)
# array([2.71828183e+00, 7.38905610e+00, 5.83461743e+14, 7.38905610e+00])

array([2.71828183e+00, 7.38905610e+00, 5.83461743e+14, 7.38905610e+00])

In [ ]:
np.log(a)
# array([0.        , 0.69314718, 3.52636052, 0.69314718])

array([0.        , 0.69314718, 3.52636052, 0.69314718])

In [ ]:
a + 10
# array([11, 12, 44, 12]) --> Plussaa arvot +10

array([11, 12, 44, 12])

In [ ]:
np.argmax(a)
# np.int64(2) --> index of the largest value

np.int64(2)